name: ReScan
options:
  bundleIdPrefix: com.rescan
  deploymentTarget:
    iOS: 17.0
targets:
  ReScan:
    type: application
    platform: iOS
    sources:
      - DIETCapture
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rescan.app
        INFOPLIST_FILE: DIETCapture/App/Info.plist
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTED_PLATFORMS: iphonesimulator iphoneos
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        PRODUCT_NAME: ReScan
